### ISSUE TITLE
Have you used any multicamera/sequence during localization like HLoc?

### ISSUE THREAD

**Issue by AddASecond** [naver/kapture-localization#17]
multi-camera/sequence can provide significant improvement in visual localization. 
for example, Hierarchical Localization - SuperPoint + SuperGlue (multi-camera) have this function: https://github.com/cvg/Hierarchical-Localization

Have kapture-localization provided similar functions?

**Comment by yocabon** [comment]
Hi,
right now we do not have multi camera pose estimation inside this repository.

I do have multi camera estimation scripts (similar to [kapture_pycolmap_localize.py](https://github.com/naver/kapture-localization/blob/main/tools/kapture_pycolmap_localize.py)) with both colmap gp3p and [MultiCameraPose](https://github.com/tsattler/MultiCameraPose) but both are running on forks of the repositories and not suited to be shared as is.

For the colmap part, I'll integrate it here when this is merged https://github.com/mihaidusmanu/pycolmap/pull/13 (I actually retracted [my pull request](https://github.com/mihaidusmanu/pycolmap/pull/10) about rig since Paul-Edouard Sarlin had a more advanced version)

For MultiCameraPose, I want [this](https://github.com/tsattler/RansacLib/pull/16) to be merged first (the MultiCameraPose changes are very similar so I'll do them afterwards) but I haven't heard anything back yet.

**Comment by Skydes** [comment]
FYI we will merge https://github.com/mihaidusmanu/pycolmap/pull/13 in the next days and release an integration with hloc.

**Comment by yocabon** [comment]
I added [kapture_pycolmap_rig_localize.py](https://github.com/naver/kapture-localization/blob/main/tools/kapture_pycolmap_rig_localize.py) and updated the Dockerfile to use the updated colmap / pycolmap.

It's not part of any pipeline right now, so to run it you have to import the colmap map obtained with the mapping pipeline with [kapture_import_colmap.py](https://github.com/naver/kapture/blob/main/tools/kapture_import_colmap.py).

the --input arg is map + query, with keypoints for all map + query images, matches for query -> map pairs for all pairs in the --pairsfile-path file; observations and points3d from the imported map

In --query, you don't need to have the reconstruction folder, only the sensors data is used.
