### ISSUE TITLE
Pairsfile for Inloc dataset

### ISSUE THREAD

**Issue by Barry-Liang** [naver/kapture-localization#22]
Hi, authors. I would like to use the image retrieval benchmark with the InLoc dataset but get no pairsfile when creating the global map. Can you provide it?
Thanks a lot!

**Comment by humenbergerm** [comment]
Hi! 

May I ask how you created the global map for Inloc? Running the normal point triangulation will not work because the images have not enough overlap in order to create sufficient 3D points.

Independent of this, the pairfiles creation is the first thing our benchmark script does. For this, global features are needed. Which one did you use?

Best,
Martin

**Comment by Barry-Liang** [comment]
Thanks for your quick response! I finally made the map using the global features.
