### ISSUE TITLE
Localization Pipeline

### ISSUE THREAD

**Issue by Mukulareddy** [naver/kapture-localization#23]
Hello authors,
I would like to know more details about the custom pipeline that is being explained. What is the ground truth model used for pose estimation for query images in kapture localization pipeline?

Thanks
Mukula

**Comment by yocabon** [comment]
Hi,
could you explain your question a bit more ?
I'm afraid I do not understand what you're asking.

"the custom pipeline that is being explained" -> where is that ?
"ground truth model" -> the query poses ?

if this is generic then all I can say is that the process to estimate query gt poses is different for every dataset, depending on what's available (odometry, lidar data...) and some form of SFM on joint (map+query). In all cases, these poses are never perfect which is why the localization evaluation is done using thresholds on distance/angle.

kapture localization assumes that the dataset come with the gt poses already computed or that their is a service (https://www.visuallocalization.net/benchmark/ http://vmnavab26.in.tum.de/RIO10/ ) available to get the localization error
